# Generated by Django 3.1 on 2021-08-21 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210821_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='created',
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
